[build]
publish = "dist"
command = "npm run build"

# Add caching headers for static assets
[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add compression and security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Permissions-Policy = "interest-cohort=()"

# Add font caching headers
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-emails"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

# Add form settings
[forms]
  # Configure form notifications
  [forms."contact"]
    email = "ty@heirloomweddingfilms.com"
    subject = "New Lead Form Submission - Heirloom Wedding Films"

[functions]
  external_node_modules = ["postmark"]
  node_bundler = "esbuild"